# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Suave Maria
email: your-email@domain.com
description: Através de tiras adesivas de micro cristais de silício, a luva Suave Maria permite uma depilação completamente indolor enquanto esfolia a tua pele, deixando-a suave!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://suavemaria.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown


sass:
  style: compressed